### ISSUE TITLE
running cordova app with plugin crashes at compiling cordova on windows 10

### ISSUE THREAD

**Issue by geminigeek** [bloodf/quasar-remote-dev-tools#2]
hi,

after installing the plugin cordova fail to compile just the process ends at 0% without any error.

here is my command

 quasar dev -m cordova -T android --ide

output 

 Dev mode.......... cordova
 Pkg quasar........ v1.11.2
 Pkg @quasar/app... v1.8.6
 Debugging......... enabled
 Running mode...... IDE (manual)

 app:extension Running "remote-dev-tools" Quasar App Extension... +0ms
 app:quasar-conf Reading quasar.conf.js +29ms
? What external IP should Quasar use? 192.168.1.10
 app:dev Checking listening address availability (192.168.1.10:8080)... +2s
 app:quasar-conf Extension(remote-dev-tools): Extending quasar.conf... +23ms
 App Extension (remote-devtools) Info: 'Adding devtools boot reference to your quasar.conf.js'
 app:webpack Extending Cordova Webpack config +1s
 app:dev Extension(remote-dev-tools): Running beforeDev hook... +283ms
Opening vue-devtools for your IP: 192.168.56.1
 app:generator Generating Webpack entry point +73ms
 app:dev-server Booting up... +13ms

 • Compiling:
 └── Cordova █                    0% compiling

> quasar info
Operating System - Windows_NT(10.0.17763) - win32/x64
NodeJs - 12.10.0

Global packages
  NPM - 6.14.5
  yarn - 1.21.1
  @quasar/cli - 1.0.6
  cordova - 9.0.0 (cordova-lib@9.0.1)

Important local packages
  quasar - 1.11.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.8.6 -- Quasar Framework local CLI
  @quasar/extras - 1.8.1 -- Quasar Framework fonts, icons and animations
  vue - 2.6.11 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.1.6 -- Official router for Vue.js 2
  vuex - 3.3.0 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed
  @babel/core - 7.9.0 -- Babel compiler core.
  webpack - 4.43.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.10.3 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.1 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*

Networking
  Host - <snip>
  VirtualBox Host-Only Network - 192.168.56.1
  Wi-Fi - 192.168.1.10

**Comment by bloodf** [comment]
With newer @quasar/cli this feature is native
